services:
  frontend:
    image: ghcr.io/gauravlamichhane/microservices-demo/frontend:latest
    mem_limit: 20m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - microservices-net
      - default

networks:
  microservices-net:
    external: true
