services:
  search-indexer: # (or audit-logger)
    image: ghcr.io/GauravLamichhane/microservices-demo/search-indexer:latest
    mem_limit: 50m
    env_file:
      - .env
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    external: true
