services:
  audit-logger:
    image: ghcr.io/gauravlamichhane/microservices-demo/audit-logger:latest
    mem_limit: 50m
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    external: true
