services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - microservices-net
      - default

  queue:
    build: .
    command: "python consumer.py"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - microservices-net
      - default

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - admin_postgres_data:/var/lib/postgresql/data/

volumes:
  admin_postgres_data:

networks:
  microservices-net:
    external: true
