services:
  backend:
    image: ghcr.io/gauravlamichhane/microservices-demo/admin:latest
    mem_limit: 150m
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - microservices-net
      - default

  queue:
    image: ghcr.io/gauravlamichhane/microservices-demo/admin:latest
    command: "python consumer.py"
    mem_limit: 60m
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - microservices-net
      - default

  celery-worker:
    image: ghcr.io/gauravlamichhane/microservices-demo/admin:latest
    command: celery -A admin worker --loglevel=info --concurrency=2
    mem_limit: 200m
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - microservices-net
      - default

  celery-beat:
    image: ghcr.io/gauravlamichhane/microservices-demo/admin:latest
    command: celery -A admin beat --loglevel=info
    mem_limit: 100m
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - microservices-net
      - default

  db:
    image: postgres:17
    mem_limit: 80m
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - admin_postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    mem_limit: 30m
    ports:
      - "6380:6379"
    restart: unless-stopped
    networks:
      - default

volumes:
  admin_postgres_data:

networks:
  microservices-net:
    external: true
